
import asyncio, json, re, html as htmlmod
from pathlib import Path
from urllib.parse import urlparse, parse_qs
from playwright.async_api import async_playwright

PRODUCT_RE = re.compile(r'data-product="([^"]+)"')
TOTAL_RE = re.compile(r'<b class="results">\s*([\d.]+)\s+risultati')
LOADER = "search/_jcr_content/root/search.loader.html"

def parse_products(body):
    out={}
    for raw in PRODUCT_RE.findall(body):
        try:
            p=json.loads(htmlmod.unescape(raw))
        except Exception:
            continue
        if p.get("code") and p.get("nome") and p.get("basePrice") is not None:
            out[str(p["code"])]=p
    return out

def parse_total(body):
    m=TOTAL_RE.search(body)
    return int(m.group(1).replace(".","")) if m else None

async def accept_cookies(page):
    b=page.locator("#onetrust-accept-btn-handler")
    try:
        if await b.count() and await b.first.is_visible():
            await b.first.click(force=True, timeout=3000)
            await page.wait_for_timeout(500)
    except Exception:
        pass

async def main():
    d=Path("probe_output")
    d.mkdir(exist_ok=True)

    captured=[]
    responses={}

    async with async_playwright() as pw:
        browser=await pw.chromium.launch(headless=True)
        ctx=await browser.new_context(locale="it-IT")
        page=await ctx.new_page()

        def on_request(req):
            if LOADER in req.url:
                h={k:v for k,v in req.headers.items()
                   if k.lower() not in {"cookie","authorization"}}
                captured.append({
                    "url":req.url,
                    "method":req.method,
                    "post_data":req.post_data,
                    "headers":h,
                })

        async def on_response(resp):
            if LOADER in resp.url:
                try:
                    body=await resp.text()
                    responses[resp.url]={
                        "status":resp.status,
                        "length":len(body),
                        "products":len(parse_products(body)),
                        "total":parse_total(body),
                        "body_sample":body[:500],
                    }
                except Exception as e:
                    responses[resp.url]={"error":str(e)}

        page.on("request",on_request)
        page.on("response",on_response)

        await page.goto(
            "https://spesaonline.conad.it/search?query=latte",
            wait_until="domcontentloaded",
            timeout=60000
        )
        await accept_cookies(page)
        await page.wait_for_timeout(1200)

        initial=await page.content()
        result={
            "initial_url":page.url,
            "initial_products":len(parse_products(initial)),
            "initial_total":parse_total(initial),
            "loader_declared":LOADER in initial,
        }

        # Click page 2 and 3 only to discover the exact request generated by Conad.
        for target in (2,3):
            await accept_cookies(page)
            link=page.locator(f'a[data-page="{target}"][title="Pagina {target}"]')
            if not await link.count():
                link=page.locator('a[aria-label="Pagina Successiva"]')
            await link.first.click(force=True, timeout=5000)
            await page.wait_for_timeout(1800)

        result["captured_requests"]=captured
        result["captured_responses"]=responses

        # Replay every captured loader request directly through Playwright's
        # request context. This is the decisive feasibility check.
        replays=[]
        seen=set()
        for req in captured:
            key=(req["method"],req["url"],req.get("post_data"))
            if key in seen:
                continue
            seen.add(key)
            kwargs={"method":req["method"],"headers":req["headers"]}
            if req.get("post_data") is not None:
                kwargs["data"]=req["post_data"]
            try:
                r=await ctx.request.fetch(req["url"],**kwargs)
                body=await r.text()
                replays.append({
                    "url":req["url"],
                    "method":req["method"],
                    "status":r.status,
                    "products":len(parse_products(body)),
                    "total":parse_total(body),
                    "length":len(body),
                    "direct_replay_ok":r.ok and len(parse_products(body))>0,
                })
            except Exception as e:
                replays.append({
                    "url":req["url"],
                    "method":req["method"],
                    "error":str(e),
                    "direct_replay_ok":False,
                })

        result["direct_replays"]=replays
        result["verdict"]=(
            "DIRECT_ENDPOINT_VALIDATED"
            if replays and all(x.get("direct_replay_ok") for x in replays)
            else "DIRECT_ENDPOINT_NOT_VALIDATED"
        )

        (d/"endpoint_probe.json").write_text(
            json.dumps(result,ensure_ascii=False,indent=2),
            encoding="utf-8"
        )
        await page.screenshot(path=str(d/"final.png"),full_page=True)
        print(json.dumps(result,ensure_ascii=False,indent=2))

        await browser.close()

if __name__=="__main__":
    asyncio.run(main())
